/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bez_glaza (https://sketchfab.com/bez_glaza)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/street-lamp-6881aa1e84b047d79860fa9297e05e22
title: Street Lamp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angle } from '../../utils/angle'

export function Lamp(props) {
  const { nodes, materials } = useGLTF('lamp.glb')
  return (
    <group {...props} dispose={null} rotation={[0, angle(180), 0]} position={[-10, 0, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh receiveShadow geometry={nodes.pCylinder14_light__0.geometry} material={materials.light} />
          <mesh castShadow receiveShadow geometry={nodes.polySurface12_lambert2_0.geometry} material={materials.lambert2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lamp.glb')
