/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Renafox (https://sketchfab.com/kryik1023)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/old-rusty-car-95baa20ebc5d4d2e869f0b549be838fe
title: Old Rusty Car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Car(props) {
  const { nodes, materials } = useGLTF('old_car.glb')
  return (
    <group {...props} dispose={null} scale={0.1} position={[20, 0, -15]} castShadow>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -4.76, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes['Object006_Material_#294_0'].geometry} material={materials.Material_294} />
          </group>
          <group position={[0, -4.76, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes['Object007_Material_#295_0'].geometry} material={materials.Material_295} />
          </group>
          <group position={[2.13, 0, -46.35]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes['Plane001_Material_#316_0'].geometry} material={materials.Material_316} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/old_car.glb')
