/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: evolveduk (https://sketchfab.com/evolveduk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/curly-palm-00f2b57dd0e844edbeb116034fa471ec
title: Curly Palm
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Palm(props) {
  const { nodes, materials } = useGLTF('/tree/palm.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.Tree_3_Tree_3Mat_0.geometry} material={materials.Tree_3Mat} />
          <mesh castShadow receiveShadow geometry={nodes.Tree_2_Tree_2Mat_0.geometry} material={materials.Tree_2Mat} />
          <mesh castShadow receiveShadow geometry={nodes.Tree_1_Tree_1Mat_0.geometry} material={materials.Tree_1Mat} />
          <mesh castShadow receiveShadow geometry={nodes.Tree_0_Tree_0Mat_0.geometry} material={materials.Tree_0Mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tree/palm.glb')
